// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NumerologiaCabalistica.Data;

#nullable disable

namespace NumerologiaCabalistica.WebApi.Migrations
{
    [DbContext(typeof(NumerologiaCabalisticaDbContext))]
    [Migration("20230321140941_CreatePostgres")]
    partial class CreatePostgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NumerologiaCabalistica.Models.DiasMesFavoraveis.DiaDoMesFavoravelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<int>("DiaFavoravel")
                        .HasColumnType("integer");

                    b.Property<int>("MesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MesId");

                    b.ToTable("DiasDoMesFavoraveis");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.DiasMesFavoraveis.MesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MesNumeral")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Mes");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.TextosNumericos.CategoriaNumeroPessoalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoriaNumero");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.TextosNumericos.TextoNumericoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TextoNumerico");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.DiasMesFavoraveis.DiaDoMesFavoravelModel", b =>
                {
                    b.HasOne("NumerologiaCabalistica.Models.DiasMesFavoraveis.MesModel", "Mes")
                        .WithMany("DiasDoMesFavoraveis")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mes");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.TextosNumericos.TextoNumericoModel", b =>
                {
                    b.HasOne("NumerologiaCabalistica.Models.TextosNumericos.CategoriaNumeroPessoalModel", "Categoria")
                        .WithMany("TextoNumerico")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.DiasMesFavoraveis.MesModel", b =>
                {
                    b.Navigation("DiasDoMesFavoraveis");
                });

            modelBuilder.Entity("NumerologiaCabalistica.Models.TextosNumericos.CategoriaNumeroPessoalModel", b =>
                {
                    b.Navigation("TextoNumerico");
                });
#pragma warning restore 612, 618
        }
    }
}
